# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
encoding: utf-8

# Site settings
author: 'chooco'

title: chooco blog
email: choo_co@naver.com
description: > # this means to ignore newlines until "baseurl:"
  모바일, 웹 그리고 프로그래밍 중심의 블로그
baseurl: "" # the subpath of your site, e.g. /blog
url: http://chooco13.github.io
github_username:  chooco13
comments: true
future: true

category_title_prefix: ''
category_dir: /

permalink: /:title/


# Build settings
markdown: kramdown
highlighter: rouge

gems:
  - jekyll-sitemap
